//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AccesoDatos.Infrastructure.Data.DataModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class evento_empresa
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public evento_empresa()
        {
            this.publicidad = new HashSet<publicidad>();
            this.tipoentrada = new HashSet<tipoentrada>();
        }
    
        public int id { get; set; }
        public string nombre { get; set; }
        public string descripcion { get; set; }
        public Nullable<System.DateTime> fecha_inicio_evento { get; set; }
        public Nullable<System.DateTime> fecha_fin_evento { get; set; }
        public Nullable<System.DateTime> fecha_inicio_publicacion { get; set; }
        public Nullable<System.DateTime> fecha_fin_publicacion { get; set; }
        public Nullable<int> id_empresa { get; set; }
        public Nullable<int> id_categoria { get; set; }
        public Nullable<int> stock_inicial { get; set; }
        public Nullable<int> stock { get; set; }
        public Nullable<int> id_ubicacion { get; set; }
        public string imagen { get; set; }
        public int valido { get; set; }
    
        public virtual categoria_evento categoria_evento { get; set; }
        public virtual empresa empresa { get; set; }
        public virtual ubicacion_evento ubicacion_evento { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<publicidad> publicidad { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tipoentrada> tipoentrada { get; set; }
    }
}
