//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AccesoDatos.Infrastructure.Data.DataModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class pago_usuario
    {
        public int id { get; set; }
        public Nullable<System.DateTime> fecha_pago { get; set; }
        public Nullable<int> id_trans { get; set; }
        public Nullable<int> monto { get; set; }
        public string factura { get; set; }
        public int valido { get; set; }
    
        public virtual transaccion_previa transaccion_previa { get; set; }
    }
}
