//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AccesoDatos.Infrastructure.Data.DataModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class publicidad
    {
        public int id { get; set; }
        public string imagen { get; set; }
        public string descripcion_larga { get; set; }
        public string descripcion_corta { get; set; }
        public Nullable<int> id_evento { get; set; }
        public int valido { get; set; }
        public Nullable<int> id_empresa { get; set; }
    
        public virtual empresa empresa { get; set; }
        public virtual evento_empresa evento_empresa { get; set; }
    }
}
