//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PlantillaComercio.Views
{
    using System;
    using System.Collections.Generic;
    
    public partial class Usuario
    {
        public int IdUsuario { get; set; }
        public string USUARIO1 { get; set; }
        public string Nombre { get; set; }
        public string Correo { get; set; }
        public string Clave { get; set; }
        public Nullable<System.DateTime> FechaNacimiento { get; set; }
        public Nullable<short> SEXO { get; set; }
        public int IdPais { get; set; }
    
        public virtual Pai Pai { get; set; }
    }
}
